@startuml [Container] Climate Ambition
!includeurl c4-plantuml/C4_Container.puml

'Roles
Person(user, "User", "End-user")
Person(moderator, "Moderator", "Responsible moderating solution")

'Main system boundary and relations internally
System_Boundary(c1, "Climate Ambition") {
    Container(app, "App", "ReactNative iOS, Android", "Mobile app")

    Container(azure_api_mgmt, "API Management", "Azure Service", "End-point for APIs in Azure. TODO: Do we need this component?") 

    Container(azure_api, "API", "Docker - .NET Core", "API implementation for solution")  

    Container(azure_app_insight, "Application Insight", "Azure Service", "Logging of API calls and source for usage metrics") 

    Container(webserver, "Webserver", "Docker", "Serving static markdown files for ambition catalog") 

    Container(github, "Github", "SaaS", "Maintain static markdown files") 


    Rel_Down(app, azure_api_mgmt, "Performs REST API calls against")  
    Rel_Down(azure_api_mgmt, azure_api, "proxies requests to")  
    Rel_Right(azure_api, azure_app_insight, "logs API requests to")  
    Rel_Down(github, webserver, "Publish to")  
}

Rel_Down(user, app, "Access app")  
Rel_Down(app, webserver, "Get markdown for ambition catalog")  
Rel_Down(moderator, github, "Maintain ambition content")  


System_Ext(google_idp,"Google Identity Provider", "Logon with Google account")
Rel_Right(app, google_idp, "Logon with") 

System_Ext(facebook,"Facebook")
System_Ext(twitter,"Twitter")
Rel_Down(app, twitter, "Share to") 
Rel_Down(app, facebook, "Share to") 


@enduml